version: '3.8'
services:
  localstack:
    image: localstack/localstack
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs

  create-resources:
    volumes:
      - "./create-resources.sh:/tmp/create-resources.sh"
    restart: "no"
    image: amazon/aws-cli:latest
    depends_on:
      localstack:
        condition: service_healthy
    environment:
      - HOSTNAME=localstack
      - AWS_DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=localstack
      - AWS_SECRET_ACCESS_KEY=localstack
      - AWS_ENDPOINT_URL=http://localstack:4566
      - ENV=local
    working_dir: /tmp
    entrypoint: [ "sh", "/tmp/create-resources.sh" ]

#  app:
#    build: .
#    container_name: spring_notification_app
#    ports:
#      - "8080:8080"
#    environment:
#      - SPRING_CLOUD_AWS_SQS_ENDPOINT=http://localstack:4566
#      - SPRING_CLOUD_AWS_REGION_STATIC=us-east-1
#      - SPRING_CLOUD_AWS_CREDENTIALS_ACCESS_KEY=test
#      - SPRING_CLOUD_AWS_CREDENTIALS_SECRET_KEY=test
#    depends_on:
#      - localstack